version: '3.2022'
services:
  nginx_certbot:
    restart: always
    image: staticfloat/nginx-certbot
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      CERTBOT_EMAIL: ${CERTBOT_EMAIL}
      ENVSUBST_VARS: FQDN
      FQDN: ${CERTBOT_DOMAIN}
    volumes:
      - ./nginx/conf.d:/etc/nginx/user.conf.d:ro
      - ./nginx/logs:/var/log/nginx
      - letsencrypt:/etc/letsencrypt

volumes:
  letsencrypt:
