version: "3.3"
services:
  research_laravel:
    container_name: research_laravel
    build:
      args:
        WWWGROUP: ${WWWGROUP}
      context: ./docker
      dockerfile: Dockerfile
    image: sail-8.1/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '8000:80'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
    volumes:
      - '.:/var/www/html'
    networks:
      - research_network

  research_vuejs:
    container_name: research_vuejs
    build:
      context: ./utg_research_fe
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"
    networks:
      - research_network

  research_nginx_certbot:
    container_name: research_nginx_certbot
    restart: always
    image: staticfloat/nginx-certbot
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      CERTBOT_EMAIL: ${CERTBOT_EMAIL}
      ENVSUBST_VARS: FQDN
      FQDN: ${CERTBOT_DOMAIN}
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
      - ./storage/logs/nginx:/var/log/nginx
    networks:
      - research_network

volumes:
  letsencrypt:

networks:
  research_network:
    driver: bridge
